#Arcadia Patch Create runtime settings
#Fri Sep 11 06:03:18 VLAT 2026
arm.enabled=false
behaviourDispatch.enabled=true
belt.enabled=true
capabilityGuard.enabled=true
chute.enabled=false
crafterSignal.enabled=true
createDrops.despawnTicks=1200
createDrops.enabled=false
factoryGauge.enabled=true
fluid.enabled=true
heatJs.enabled=true
itemDrain.enabled=true
master.enabled=true
redstoneLink.enabled=true
throttle.mode=OFF
throttle.staticInterval=2
