version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 128
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 4.0
paintingCulling = true
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
createfood = true
hybrid_aquatic = true
engineersdecor = true
mcwfences = true
farmersdelight = true
mcwroofs = true
upgrade_aquatic = true
mcwbyg = true
mcwwindows = true
alexsmobs = true
createpropulsion = true
createcolonies = true
create_optical = true
mcwstairs = true
rocketnautics_addon = true
copycats = true
minecolonytax = true
veggiesdelight = true
domum_ornamentum = true
createnuclear_radiation = true
citadel = true
createdieselgenerators = true
create_enchantment_industry = true
create_submarine = true
aeronautics_utility_objects = true
mcwlights = true
mcwbridges = true
mcwtrpdoors = true
railways = true
bellsandwhistles = true
fruitsdelight = true
eclipticseasons = true
mcwholidays = true
ftbquests = true
minecolonies_compatibility = true
biomesoplenty = true
create_radar = true
sophisticatedbackpacks = true
adpother = true
offroad = true
mcwdoors = true
create_hypertube = true
cratedelight = true
createthrusters = true
createbigcannons = true
creategeoresonance = true
adfinders = true
petrolpark = true
aquaculture = true
minecolonies = true
structurize = true
colony4cc = true
create = true
aeronautics = true
smog = true
immersivepetroleum = true
simulated = true
interiors = true
vsfluidlink = true
gravestone = true
biomeswevegone = true
multipiston = true
minecraft = true
solarpunk = true
create_dragons_plus = true
create_connected = true
create_mob_spawners = true
createdeco = true
mcwfurnitures = true
rocketnautics = true
createaddition = true
aquaculturedelight = true
create_mobile_packages = true
waystones = true
computercraft = true
petrolsparts = true
immersiveengineering = true
createnuclear = true
create_aquatic_ambitions = true
delightfulcreators = true
surfacesamples = true
cloudworks_api = true
